#!/usr/bin/env Rscript
model1=read.csv('model1/pdbbind-2007-core-statistics.csv')
model2=read.csv('model2/pdbbind-2007-core-statistics.csv')
model3=read.csv('model3/pdbbind-2007-core-statistics.csv')
model4=read.csv('model4/pdbbind-2007-core-statistics.csv')
rmse=c(model1['rmse'],model2['rmse'],model3['rmse'],model4['rmse'])
sdev=c(model1['sdev'],model2['sdev'],model3['sdev'],model4['sdev'])
pcor=c(model1['pcor'],model2['pcor'],model3['pcor'],model4['pcor'])
scor=c(model1['scor'],model2['scor'],model3['scor'],model4['scor'])
kcor=c(model1['kcor'],model2['kcor'],model3['kcor'],model4['kcor'])
names(rmse)=c('1','2','3','4')
names(sdev)=c('1','2','3','4')
names(pcor)=c('1','2','3','4')
names(scor)=c('1','2','3','4')
names(kcor)=c('1','2','3','4')
#pdf('rmse.pdf')
tiff('rmse.tiff',compression='lzw')
boxplot(rmse,main=sprintf('Boxplot of RMSE of models 1, 2, 3 and 4 trained on\nPDBbind v2007 refined set minus core set (N = 1105)'),xlab='Model',ylab='RMSE (Å)')
#pdf('sdev.pdf')
tiff('sdev.tiff',compression='lzw')
boxplot(sdev,main=sprintf('Boxplot of SD of models 1, 2, 3 and 4 trained on\nPDBbind v2007 refined set minus core set (N = 1105)'),xlab='Model',ylab='SD (Å)')
#pdf('pcor.pdf')
tiff('pcor.tiff',compression='lzw')
boxplot(pcor,main=sprintf('Boxplot of Rp of models 1, 2, 3 and 4 trained on\nPDBbind v2007 refined set minus core set (N = 1105)'),xlab='Model',ylab='Pearson correlation coefficient')
#pdf('scor.pdf')
tiff('scor.tiff',compression='lzw')
boxplot(scor,main=sprintf('Boxplot of Rs of models 1, 2, 3 and 4 trained on\nPDBbind v2007 refined set minus core set (N = 1105)'),xlab='Model',ylab='Spearman correlation coefficient')
#pdf('kcor.pdf')
tiff('kcor.tiff',compression='lzw')
boxplot(kcor,main=sprintf('Boxplot of Rk of models 1, 2, 3 and 4 trained on\nPDBbind v2007 refined set minus core set (N = 1105)'),xlab='Model',ylab='Kendall correlation coefficient')
