#!/usr/bin/env Rscript
model3=read.csv('model3/pdbbind2007-core-statistics.csv')
model4=read.csv('model4/pdbbind2007-core-statistics.csv')
model5=read.csv('model5/pdbbind2007-core-statistics.csv')
rmse=c(model3['rmse'],model4['rmse'],model5['rmse'])
sdev=c(model3['sdev'],model4['sdev'],model5['sdev'])
pcor=c(model3['pcor'],model4['pcor'],model5['pcor'])
scor=c(model3['scor'],model4['scor'],model5['scor'])
kcor=c(model3['kcor'],model4['kcor'],model5['kcor'])
names(rmse)=c('3','4','5')
names(sdev)=c('3','4','5')
names(pcor)=c('3','4','5')
names(scor)=c('3','4','5')
names(kcor)=c('3','4','5')
#pdf('rmse.pdf')
tiff('rmse.tiff',compression='lzw')
boxplot(rmse,main='Boxplot of RMSE of models 3, 4 and 5',xlab='Model',ylab='RMSE (Å)')
#pdf('sdev.pdf')
tiff('sdev.tiff',compression='lzw')
boxplot(sdev,main='Boxplot of SD of models 3, 4 and 5',xlab='Model',ylab='SD (Å)')
#pdf('pcor.pdf')
tiff('pcor.tiff',compression='lzw')
boxplot(pcor,main='Boxplot of Pearson correlation coefficient of models 3, 4 and 5',xlab='Model',ylab='Pearson correlation coefficient')
#pdf('scor.pdf')
tiff('scor.tiff',compression='lzw')
boxplot(scor,main='Boxplot of Spearman correlation coefficient of models 3, 4 and 5',xlab='Model',ylab='Spearman correlation coefficient')
#pdf('kcor.pdf')
tiff('kcor.tiff',compression='lzw')
boxplot(kcor,main='Boxplot of Kendall correlation coefficient of models 3, 4 and 5',xlab='Model',ylab='Kendall correlation coefficient')
