#!/usr/bin/env Rscript
v=commandArgs(trailingOnly=T)[1]
model1=read.csv(sprintf('model1/pdbbind-%s-core-statistics.csv',v))
model2=read.csv(sprintf('model2/pdbbind-%s-core-statistics.csv',v))
model3=read.csv(sprintf('model3/pdbbind-%s-core-statistics.csv',v))
model4=read.csv(sprintf('model4/pdbbind-%s-core-statistics.csv',v))
rmse=c(model1['rmse'],model2['rmse'],model3['rmse'],model4['rmse'])
sdev=c(model1['sdev'],model2['sdev'],model3['sdev'],model4['sdev'])
pcor=c(model1['pcor'],model2['pcor'],model3['pcor'],model4['pcor'])
scor=c(model1['scor'],model2['scor'],model3['scor'],model4['scor'])
kcor=c(model1['kcor'],model2['kcor'],model3['kcor'],model4['kcor'])
names(rmse)=c('1','2','3','4')
names(sdev)=c('1','2','3','4')
names(pcor)=c('1','2','3','4')
names(scor)=c('1','2','3','4')
names(kcor)=c('1','2','3','4')
#pdf(sprintf('pdbbind-%s-core-rmse.pdf',v))
tiff(sprintf('pdbbind-%s-core-rmse.tiff',v),compression='lzw')
boxplot(rmse,main=sprintf('Boxplot of RMSE of models 1, 2, 3 and 4\non PDBbind v2007 core set (N = 195)'),xlab='Model',ylab='Root Mean Square Error (Å)')
#pdf(sprintf('pdbbind-%s-core-sdev.pdf',v))
tiff(sprintf('pdbbind-%s-core-sdev.tiff',v),compression='lzw')
boxplot(sdev,main=sprintf('Boxplot of SD of models 1, 2, 3 and 4\non PDBbind v2007 core set (N = 195)'),xlab='Model',ylab='Standard Deviation (Å)')
#pdf(sprintf('pdbbind-%s-core-pcor.pdf',v))
tiff(sprintf('pdbbind-%s-core-pcor.tiff',v),compression='lzw')
boxplot(pcor,main=sprintf('Boxplot of Rp of models 1, 2, 3 and 4\non PDBbind v2007 core set (N = 195)'),xlab='Model',ylab='Pearson correlation coefficient')
#pdf(sprintf('pdbbind-%s-core-scor.pdf',v))
tiff(sprintf('pdbbind-%s-core-scor.tiff',v),compression='lzw')
boxplot(scor,main=sprintf('Boxplot of Rs of models 1, 2, 3 and 4\non PDBbind v2007 core set (N = 195)'),xlab='Model',ylab='Spearman correlation coefficient')
#pdf(sprintf('pdbbind-%s-core-kcor.pdf',v))
tiff(sprintf('pdbbind-%s-core-kcor.tiff',v),compression='lzw')
boxplot(kcor,main=sprintf('Boxplot of Rk of models 1, 2, 3 and 4\non PDBbind v2007 core set (N = 195)'),xlab='Model',ylab='Kendall correlation coefficient')
