#!/usr/bin/env Rscript
iyp=read.csv('pdbbind2007-core-iyp.csv',check.names=F)
pdf('pdbbind2007-core-iyp.pdf')
plot(iyp[,2], iyp[,3], asp=1, xlim=c(2,14), ylim=c(2,14), xlab="Measured binding affinity (pKd)", ylab="Predicted binding affinity (pKd)")
abline(lm(iyp[,3] ~ iyp[,2]))
grid()
n=nrow(iyp)
se=sum((iyp[3] - iyp[2])^2)
rmse=sqrt(se/n)
sdev=sqrt(se/(n-1))
pcor=cor(iyp[3], iyp[2], method="pearson")
scor=cor(iyp[3], iyp[2], method="spearman")
kcor=cor(iyp[3], iyp[2], method="kendall")
title(sprintf("RMSE=%.2f, Rp=%.3f, Rs=%.3f on PDBbind v2007 core set (N = %d)", rmse, pcor, scor, n))