#!/usr/bin/env Rscript
v=commandArgs(trailingOnly=T)[1]
iyp=read.csv(sprintf("pdbbind-%s-tst-iyp.csv",v),check.names=F)
#pdf(sprintf("pdbbind-%s-tst-iyp.pdf",v))
tiff(sprintf("pdbbind-%s-tst-iyp.tiff",v),compress="lzw")
plot(iyp[,2], iyp[,3], asp=1, xlim=c(2,14), ylim=c(2,14), xlab="Measured binding affinity (pKd)", ylab="Predicted binding affinity (pKd)")
abline(lm(iyp[,3] ~ iyp[,2]))
grid()
n=nrow(iyp)
se=sum((iyp[3] - iyp[2])^2)
rmse=sqrt(se/n)
sdev=sqrt(se/(n-1))
pcor=cor(iyp[3], iyp[2], method="pearson")
scor=cor(iyp[3], iyp[2], method="spearman")
kcor=cor(iyp[3], iyp[2], method="kendall")
title(sprintf("RMSE=%.2f, SD=%.2f, Rp=%.3f, Rs=%.3f", rmse, sdev, pcor, scor))
