#!/usr/bin/env Rscript
a=commandArgs(trailingOnly=T)
s=a[1]
v=a[2]
model1=read.csv(sprintf("model1/set%s/pdbbind-%s-tst-stat.csv",s,2007))
model2=read.csv(sprintf("model2/set%s/pdbbind-%s-tst-stat.csv",s,v))
model3=read.csv(sprintf("model3/set%s/pdbbind-%s-tst-stat.csv",s,v))
model4=read.csv(sprintf("model4/set%s/pdbbind-%s-tst-stat.csv",s,v))
# Use boxplot() to create pdbbind-$v-tst-*-boxplot.tiff
rmse=c(model1["rmse"],model2["rmse"],model3["rmse"],model4["rmse"])
sdev=c(model1["sdev"],model2["sdev"],model3["sdev"],model4["sdev"])
pcor=c(model1["pcor"],model2["pcor"],model3["pcor"],model4["pcor"])
scor=c(model1["scor"],model2["scor"],model3["scor"],model4["scor"])
kcor=c(model1["kcor"],model2["kcor"],model3["kcor"],model4["kcor"])
names(rmse)=c("1","2","3","4")
names(sdev)=c("1","2","3","4")
names(pcor)=c("1","2","3","4")
names(scor)=c("1","2","3","4")
names(kcor)=c("1","2","3","4")
tiff(sprintf("pdbbind-%s-tst-rmse-boxplot.tiff",v),compression="lzw")
par(cex.lab=1.3,cex.axis=1.3,cex.main=1.3)
boxplot(rmse,main="Boxplot of RMSE of models 1, 2, 3 and 4",xlab="Model",ylab="RMSE",range=0)
tiff(sprintf("pdbbind-%s-tst-sdev-boxplot.tiff",v),compression="lzw")
par(cex.lab=1.3,cex.axis=1.3,cex.main=1.3)
boxplot(sdev,main="Boxplot of SD of models 1, 2, 3 and 4",xlab="Model",ylab="SD",range=0)
tiff(sprintf("pdbbind-%s-tst-pcor-boxplot.tiff",v),compression="lzw")
par(cex.lab=1.3,cex.axis=1.3,cex.main=1.3)
boxplot(pcor,main="Boxplot of Rp of models 1, 2, 3 and 4",xlab="Model",ylab="Rp",range=0)
tiff(sprintf("pdbbind-%s-tst-scor-boxplot.tiff",v),compression="lzw")
par(cex.lab=1.3,cex.axis=1.3,cex.main=1.3)
boxplot(scor,main="Boxplot of Rs of models 1, 2, 3 and 4",xlab="Model",ylab="Rs",range=0)
tiff(sprintf("pdbbind-%s-tst-kcor-boxplot.tiff",v),compression="lzw")
par(cex.lab=1.3,cex.axis=1.3,cex.main=1.3)
boxplot(kcor,main="Boxplot of Rk of models 1, 2, 3 and 4",xlab="Model",ylab="Rk",range=0)
# Use plot() to create pdbbind-$v-tst-*-median.tiff
rmse=c(median(model1["rmse"][,1]),median(model2["rmse"][,1]),median(model3["rmse"][,1]),median(model4["rmse"][,1]))
sdev=c(median(model1["sdev"][,1]),median(model2["sdev"][,1]),median(model3["sdev"][,1]),median(model4["sdev"][,1]))
pcor=c(median(model1["pcor"][,1]),median(model2["pcor"][,1]),median(model3["pcor"][,1]),median(model4["pcor"][,1]))
scor=c(median(model1["scor"][,1]),median(model2["scor"][,1]),median(model3["scor"][,1]),median(model4["scor"][,1]))
kcor=c(median(model1["kcor"][,1]),median(model2["kcor"][,1]),median(model3["kcor"][,1]),median(model4["kcor"][,1]))
tiff(sprintf("pdbbind-%s-tst-rmse-median.tiff",v),compression="lzw")
par(cex.lab=1.3,cex.axis=1.3,cex.main=1.3)
plot(1:4,rmse,main="Median of RMSE of models 1, 2, 3 and 4",xlab="Model",ylab="RMSE",pch=3,xaxt="n")
axis(1,1:4)
tiff(sprintf("pdbbind-%s-tst-sdev-median.tiff",v),compression="lzw")
par(cex.lab=1.3,cex.axis=1.3,cex.main=1.3)
plot(1:4,sdev,main="Median of SD of models 1, 2, 3 and 4",xlab="Model",ylab="SD",pch=3,xaxt="n")
axis(1,1:4)
tiff(sprintf("pdbbind-%s-tst-pcor-median.tiff",v),compression="lzw")
par(cex.lab=1.3,cex.axis=1.3,cex.main=1.3)
plot(1:4,pcor,main="Median of Rp of models 1, 2, 3 and 4",xlab="Model",ylab="Rp",pch=3,xaxt="n")
axis(1,1:4)
tiff(sprintf("pdbbind-%s-tst-scor-median.tiff",v),compression="lzw")
par(cex.lab=1.3,cex.axis=1.3,cex.main=1.3)
plot(1:4,scor,main="Median of Rs of models 1, 2, 3 and 4",xlab="Model",ylab="Rs",pch=3,xaxt="n")
axis(1,1:4)
tiff(sprintf("pdbbind-%s-tst-kcor-median.tiff",v),compression="lzw")
par(cex.lab=1.3,cex.axis=1.3,cex.main=1.3)
plot(1:4,kcor,main="Median of Rk of models 1, 2, 3 and 4",xlab="Model",ylab="Rk",pch=3,xaxt="n")
axis(1,1:4)
