#!/usr/bin/env Rscript
s=commandArgs(trailingOnly=T)[1]
v=commandArgs(trailingOnly=T)[2]
model1=read.csv(sprintf("model1/set%s/pdbbind-%s-tst-stat.csv",s,2007))
model2=read.csv(sprintf("model2/set%s/pdbbind-%s-tst-stat.csv",s,v))
model3=read.csv(sprintf("model3/set%s/pdbbind-%s-tst-stat.csv",s,v))
model4=read.csv(sprintf("model4/set%s/pdbbind-%s-tst-stat.csv",s,v))
rmse=c(model1["rmse"],model2["rmse"],model3["rmse"],model4["rmse"])
sdev=c(model1["sdev"],model2["sdev"],model3["sdev"],model4["sdev"])
pcor=c(model1["pcor"],model2["pcor"],model3["pcor"],model4["pcor"])
scor=c(model1["scor"],model2["scor"],model3["scor"],model4["scor"])
kcor=c(model1["kcor"],model2["kcor"],model3["kcor"],model4["kcor"])
names(rmse)=c("1","2","3","4")
names(sdev)=c("1","2","3","4")
names(pcor)=c("1","2","3","4")
names(scor)=c("1","2","3","4")
names(kcor)=c("1","2","3","4")
tiff(sprintf("pdbbind-%s-tst-rmse-boxplot.tiff",v),compression="lzw")
boxplot(rmse,main="Boxplot of RMSE of models 1, 2, 3 and 4",xlab="Model",ylab="Root Mean Square Error (Å)")
tiff(sprintf("pdbbind-%s-tst-rmse-median.tiff",v),compression="lzw")
boxplot(rmse,main="Median of RMSE of models 1, 2, 3 and 4",xlab="Model",ylab="Root Mean Square Error (Å)",outline=F,boxlty=0,whisklty=0,staplelty=0)
tiff(sprintf("pdbbind-%s-tst-sdev-boxplot.tiff",v),compression="lzw")
boxplot(sdev,main="Boxplot of SD of models 1, 2, 3 and 4",xlab="Model",ylab="Standard Deviation (Å)")
tiff(sprintf("pdbbind-%s-tst-sdev-median.tiff",v),compression="lzw")
boxplot(sdev,main="Median of SD of models 1, 2, 3 and 4",xlab="Model",ylab="Standard Deviation (Å)",outline=F,boxlty=0,whisklty=0,staplelty=0)
tiff(sprintf("pdbbind-%s-tst-pcor-boxplot.tiff",v),compression="lzw")
boxplot(pcor,main="Boxplot of Rp of models 1, 2, 3 and 4",xlab="Model",ylab="Pearson correlation coefficient")
tiff(sprintf("pdbbind-%s-tst-pcor-median.tiff",v),compression="lzw")
boxplot(pcor,main="Median of Rp of models 1, 2, 3 and 4",xlab="Model",ylab="Pearson correlation coefficient",outline=F,boxlty=0,whisklty=0,staplelty=0)
tiff(sprintf("pdbbind-%s-tst-scor-boxplot.tiff",v),compression="lzw")
boxplot(scor,main="Boxplot of Rs of models 1, 2, 3 and 4",xlab="Model",ylab="Spearman correlation coefficient")
tiff(sprintf("pdbbind-%s-tst-scor-median.tiff",v),compression="lzw")
boxplot(scor,main="Median of Rs of models 1, 2, 3 and 4",xlab="Model",ylab="Spearman correlation coefficient",outline=F,boxlty=0,whisklty=0,staplelty=0)
tiff(sprintf("pdbbind-%s-tst-kcor-boxplot.tiff",v),compression="lzw")
boxplot(kcor,main="Boxplot of Rk of models 1, 2, 3 and 4",xlab="Model",ylab="Kendall correlation coefficient")
tiff(sprintf("pdbbind-%s-tst-kcor-median.tiff",v),compression="lzw")
boxplot(kcor,main="Median of Rk of models 1, 2, 3 and 4",xlab="Model",ylab="Kendall correlation coefficient")
