#!/usr/bin/env Rscript
vs=read.table(file("stdin"))
ntrn=c()
rmse=c()
sdev=c()
pcor=c()
scor=c()
kcor=c()
for (i in 1:nrow(vs))
{
	v=vs[i,1]
	trn_stat=read.csv(sprintf("pdbbind-%s-trn-stat.csv",v))
	tst_stat=read.csv(sprintf("pdbbind-%s-tst-stat.csv",v))
	ntrn=c(ntrn,trn_stat["n"][1,1])
	rmse=c(rmse,tst_stat["rmse"][1])
	sdev=c(sdev,tst_stat["sdev"][1])
	pcor=c(pcor,tst_stat["pcor"][1])
	scor=c(scor,tst_stat["scor"][1])
	kcor=c(kcor,tst_stat["kcor"][1])
}
names(rmse)=ntrn
names(sdev)=ntrn
names(pcor)=ntrn
names(scor)=ntrn
names(kcor)=ntrn
tiff("tst-rmse-boxplot.tiff",compression="lzw")
par(cex.lab=1.3,cex.axis=1.3,cex.main=1.3)
boxplot(rmse,main="Boxplot of RMSE",xlab="Number of training complexes",ylab="RMSE",range=0)
tiff("tst-rmse-median.tiff",compression="lzw")
par(cex.lab=1.3,cex.axis=1.3,cex.main=1.3)
boxplot(rmse,main="Median of RMSE",xlab="Number of training complexes",ylab="RMSE",range=0,boxlty=0,whisklty=0,staplelty=0)
tiff("tst-sdev-boxplot.tiff",compression="lzw")
par(cex.lab=1.3,cex.axis=1.3,cex.main=1.3)
boxplot(sdev,main="Boxplot of SD",xlab="Number of training complexes",ylab="SD",range=0)
tiff("tst-sdev-median.tiff",compression="lzw")
par(cex.lab=1.3,cex.axis=1.3,cex.main=1.3)
boxplot(sdev,main="Median of SD",xlab="Number of training complexes",ylab="SD",range=0,boxlty=0,whisklty=0,staplelty=0)
tiff("tst-pcor-boxplot.tiff",compression="lzw")
par(cex.lab=1.3,cex.axis=1.3,cex.main=1.3)
boxplot(pcor,main="Boxplot of Rp",xlab="Number of training complexes",ylab="Rp",range=0)
tiff("tst-pcor-median.tiff",compression="lzw")
par(cex.lab=1.3,cex.axis=1.3,cex.main=1.3)
boxplot(pcor,main="Median of Rp",xlab="Number of training complexes",ylab="Rp",range=0,boxlty=0,whisklty=0,staplelty=0)
tiff("tst-scor-boxplot.tiff",compression="lzw")
par(cex.lab=1.3,cex.axis=1.3,cex.main=1.3)
boxplot(scor,main="Boxplot of Rs",xlab="Number of training complexes",ylab="Rs",range=0)
tiff("tst-scor-median.tiff",compression="lzw")
par(cex.lab=1.3,cex.axis=1.3,cex.main=1.3)
boxplot(scor,main="Median of Rs",xlab="Number of training complexes",ylab="Rs",range=0,boxlty=0,whisklty=0,staplelty=0)
tiff("tst-kcor-boxplot.tiff",compression="lzw")
par(cex.lab=1.3,cex.axis=1.3,cex.main=1.3)
boxplot(kcor,main="Boxplot of Rk",xlab="Number of training complexes",ylab="Rk",range=0)
tiff("tst-kcor-median.tiff",compression="lzw")
par(cex.lab=1.3,cex.axis=1.3,cex.main=1.3)
boxplot(kcor,main="Median of Rk",xlab="Number of training complexes",ylab="Rk",range=0,boxlty=0,whisklty=0,staplelty=0)
